### ISSUE TITLE
Rectangular window frame image overlay to drop on a window pane

### ISSUE THREAD

**Issue by jwietelmann** [joeellis/barcamp2012#11]
Calling all Photoshoppers: It would be pretty cool now that we have the window pane grid to be able to drop a stylized window frame image over any of the background window panes. This would make it easier for the less design-inclined folks like myself to make content that looks good and like it's part of the window.

It also would have some promising potential for shenanigans like velociraptor whack-a-mole as windows open and raptors jump out or... whatever, you get the idea.

**Comment by joeellis** [comment]
So I was asked this by @bhuga by email:

"what are the odds i could get you to slice the building such that the
exterior is a separate layer with transparent windows? that would let
us assign a z-index for things that are inside the windows and hat
wobble man wont jut outside. it will take a bit more to load but i
think it would be a lot cooler."

I assume this is on the same issue, yes?

**Comment by jwietelmann** [comment]
That's kind of different because in this case I'm thinking of things that might pop _out_ of the window. So I might want some image to stop at the left/bottom edges of the window but overlap the top/right edges. I stil like @bhuga's idea, but it's a different animal.

**Comment by joeellis** [comment]
Well I'm thinking if we did @bhuga's idea, and the windows were somehow positioned through css using the grid you setup in their own "window" classes, then all we'd need to do is just make more window classes for different types of windows (regular / open / closed / damaged / etc).  I'm wondering if that might be a better approach rather than just overlaying a graphic over what currently exists (plus we get the z-index niceness).  Agree / disagree / I'm thinking too much about this?

**Comment by jwietelmann** [comment]
I'm just still not really sure how that helps me easily get rectangular content into a trapezoidal window. Seems like slapping a stylized window graphic over the background window on an as-needed basis would be a lot simpler in that case. Or maybe I just don't understand what you're saying ¯(°_o)/¯

**Comment by bhuga** [comment]
The two approaches do different things:
- The building as an overlay allows things to be inside the building
- The windows as overlays allow things to be coming out of the building

The former makes it easier to do things like put celery man in a window without having to do any image editing. But the latter makes things like the raptors coming out of the windows near the top possible.

I think both could be supported. as long as the latter would be done in css, there's no reason it could not be done _as well_ as layer the windows, and just cover up the transparent-window-to-background thing.

**Comment by joeellis** [comment]
I'll email John and see what it would take to just transparentize the windows (most likely this is very minor), and then I'll re-add the building graphic with a relatively high z-index so by default most things appear behind the window.  

Then I'll also include a separate standalone window png graphic (with psd included in /src so people can make other windows stylings), and people can use that in their own classes (together with a higher z-index than the building) and just overlay it stuff on top of the building.

Would doing this help solve both issues?

**Comment by joeellis** [comment]
And if I'm still off the mark, my apologies for being an idiot, so feel free to just explain it to me in a patronizing voice like I'm a 5 year old child.

**Comment by bhuga** [comment]
I think that would do great. Just make sure the body's background is the current 'inside the window' color, and it shouldn't affect loading times at all.

**Comment by joeellis** [comment]
Added the building in.  The inside of the windows are currently "blue", but I think it's fine for now (they can be a reflection of the sky or something).
