### ISSUE TITLE
Make some helicopters fly around the dino

### ISSUE THREAD

**Issue by jwietelmann** [joeellis/barcamp2012#13]
![heli](http://www.pixeljoint.com/files/icons/helicopter__r101960271.gif)

**Comment by joeellis** [comment]
This copter is already added in per Joel's other pull request if anyone wants to start making them move around.  When I finish up with the other building / window / transparency stuff, I'll probably start something on this

**Comment by joeellis** [comment]
Done and going to bed.  Feel free to add more where needed.  If someone has a graphic of them shooting machine guns, it'd be even radder though
