### ISSUE TITLE
Make the dino/very top of building into an absolutely-positioned div

### ISSUE THREAD

**Issue by jwietelmann** [joeellis/barcamp2012#14]
Otherwise the helicopters will only be able to fly in _front_ of Sergeant Rawr.

**Comment by bhuga** [comment]
you are the wind beneath my wings.

also, i love that he has a name. sergeant rawr.

**Comment by jwietelmann** [comment]
We're going to do a VoteIt on his name at some point. Until then, I'm just going to call him something different every time.

**Comment by joeellis** [comment]
K, I'll take care of this one as well when I change up the building.  John said he'd be getting me a transparent window building tonight.

**Comment by bhuga** [comment]
Joel, go add the ability for me to associate a picture with a voteit please.

**Comment by jwietelmann** [comment]
@bhuga - I'm kind of ambiguous on what you're asking. Are you looking for a barcampnola2012 feature or a VoteIt feature? You can already add image attachments to a VoteIt. We've also got an embeddable widget now, but the code isn't publicized on the site anywhere yet: http://joelatvoteit.blogspot.com/2012/05/voteit-is-getting-embeddable-widget.html

**Comment by joeellis** [comment]
BTW, don't make / publicize a VoteIt for the dinosaur.  We're going to be setting that up and announcing one on Tuesday at the Net2NO thing, if you didn't already know this.

**Comment by jwietelmann** [comment]
Yeah I figured ya'll had something in the fire. BTW, what do you think of a VoteIt for people to propose their talks? I mean if that's not too antithetical to Barcamp. Maybe slap a disclaimer on it: "This is Barcamp, so even if everybody hates your talk idea, you're obviously free to shout it from the rooftops anyway."

**Comment by bhuga** [comment]
Oh. there's no image attachment on the 'create a vote screen' so i figured it did not work.

and understood, joe.

i think a 'talks i want to see' voteit would not be bad. it would let a few bubble to the top, we could announce both at net2no.

**Comment by jwietelmann** [comment]
@bhuga - You're probably on the not-yet-signed-in create screen. We don't let you upload anything until you're signed in, so that version doesn't include attachments.

**Comment by bhuga** [comment]
No, turns out i just missed the 'manage attachments' button. I was looking for 'image'.

**Comment by joeellis** [comment]
Fixed the dino to be absolutely positioned, just waiting on the building from John

**Comment by joeellis** [comment]
Done
