### ISSUE TITLE
↑↑↓↓←→←→ba

### ISSUE THREAD

**Issue by toots** [joeellis/barcamp2012#18]
I want to add this sequence of keys but I have no idea for the handler.. Anyone? :-)

**Comment by joeellis** [comment]
Hey Romain, take a look at this:

http://files.www.gethifi.com/posts/konami/konami.js

**Comment by joeellis** [comment]
Taken from here: http://files.www.gethifi.com/posts/konami/index.html

**Comment by toots** [comment]
Ha cool! What do you think that could trigger?

**Comment by joeellis** [comment]
Hrm, it could trigger this: http://www.zurb.com/playground/jquery-raptorize they actually have a konami thing set up

**Comment by toots** [comment]
Deal!
