### ISSUE TITLE
Vertical alignment of window panes is off

### ISSUE THREAD

**Issue by jwietelmann** [joeellis/barcamp2012#20]
![oops](http://i.imgur.com/6doDS.png)

**Comment by joeellis** [comment]
K, that's different from what I'm seeing, which browser are you looking through?

Also, delete your tweet, Tritico isn't suppose to see anything before Tuesday, remember?

**Comment by jwietelmann** [comment]
Oh I'm not sure I entirely grokked that part about hiding from Tritico.

I'm looking at Chrome, and I've done a `git fetch upstream && git merge upstream/master` several times now. I'm definitely getting the upstream updates, and trying to open a pull request between my master branch and yours says that we're already up to date.

**Comment by jwietelmann** [comment]
It looks right on Firefox... well that's depressing...

**Comment by joeellis** [comment]
No problem on the Tritico part, but him not seeing it is probably the only reason I do most of this.

Also, I just updated with my current work (heli moving stuff), but do a pull and see if it works.  Might just be a cached stylesheet?

**Comment by joeellis** [comment]
Oh also, did you restart rack?  Shouldn't affect it, but still, it's finicky

**Comment by jwietelmann** [comment]
Restarted rack, tried just opening the index.html file without rack. Also I don't see your heli moving stuff anywhere in your Github commit log.

**Comment by joeellis** [comment]
Ah shit just looked, I had needed to do a pull first.  Just pushed, try again

**Comment by jwietelmann** [comment]
Cool helicopters. Alignment is still broken :(

**Comment by joeellis** [comment]
Ahhh weird, I was using Canary, but when I used actual Chrome, they are broken on my end as well.

**Comment by vaxinate** [comment]
yeah i see the alignment issue in chrome as well.

**Comment by joeellis** [comment]
I think I got a fix, do another pull

**Comment by jwietelmann** [comment]
Sweet. Looks right in both Chrome and Firefox.

**Comment by joeellis** [comment]
Yea, I had set one of the panel settings to be something like "margin-bottom: 24.5px" earlier in the day, and since it worked on Canary, didn't notice the problem.  I imagine Firefox was ok because it recognizes the extra .5, whereas perhaps Chrome only deals with integers, hence the discrepancy. Anyways, just setting it back seemed to work. 

## 

Joe Ellis
Squarefour Digital Media
504.920.8248
