### ISSUE TITLE
Maybe a mobile version of the site?

### ISSUE THREAD

**Issue by EdwardReed** [joeellis/barcamp2012#49]
A simple layout or maybe shrink down of the building?

**Comment by joeellis** [comment]
Eddie,

Definitely, if you wanna start a pull request for it, I'll help where
possible. Let me know if you need new / different graphics

On Jun 7, 2012, at 6:07 PM, EDREED
reply@reply.github.com
wrote:

**Comment by EdwardReed** [comment]
Ok I made a pull request for it but I forgot to compile css to sass... Im doing that now...

**Comment by EdwardReed** [comment]
Never mind i dont know how??

**Comment by joeellis** [comment]
Have you tried running the "scss --watch . " command in the terminal and resaving the file?

**Comment by EdwardReed** [comment]
Yea Its done... I have no idea why I have so many untracked files that keep re-updating ??
